CC=gcc
CFLAGS=-Wall -O3
LDFLAGS=-lm

# TODO: complete the Makefile

all: integral_mc_seq 

integral_mc_seq: integral_mc_seq.c
	$(CC) $(CFLAGS) -o integral_mc_seq integral_mc_seq.c $(LDFLAGS)

clean:
	rm -f integral_mc_seq
