# Makefile: the slow way
CC=gcc
CFLAGS=-Wall

all: fork0 fork1 fork2 fork3 fork4
.PHONY:all


fork0: fork0.c
	$(CC) $(CFLAGS) -o fork0 fork0.c

fork1: fork1.c
	$(CC) $(CFLAGS) -o fork1 fork1.c

fork2: fork2.c
	$(CC) $(CFLAGS) -o fork2 fork2.c

fork3: fork3.c
	$(CC) $(CFLAGS) -o fork3 fork3.c

fork4: fork4.c
	$(CC) $(CFLAGS) -o fork4 fork4.c




clean:
	rm -f fork0 fork1 fork2 fork3 fork4
.PHONY:clean
